### ISSUE TITLE
Question: How to launch the ico website dashboard in browser after setup successfully? 

### ISSUE THREAD

**Issue by inix** [JincorTech/backend-ico-dashboard#123]
Hi,dear developers，I have no idea how to start web dashboard after setup docker env successfully.
I have logined the container and generate JWT token successfully.
I have googled but no luck.
Could you help?

Thanks

dev env
Mac OS serria,docker 1.8

**Comment by hlogeon** [comment]
Hello! Thanks for attention to our little project. Could you please describe your problem?

**Comment by inix** [comment]
@hlogeon
Hi,I want to visit ico web portal dashboard via browser connection is refused.
I have setup docker env and non run serve successfully.I set FRONT_URL as localhost,visit http://localhost or http://localhost:3000,can not visit.
Thanks

**Comment by hlogeon** [comment]
Hello! You need to build  and run frontend for this purpose and configure it to work with backend you already managed to work.
https://github.com/secret-tech/frontend-ico-dashboard

**Comment by inix** [comment]
@hlogeon 
Hi,I will try the repo you have pasted.
Thanks.
