### ISSUE TITLE
No container found for ico_1

### ISSUE THREAD

**Issue by vm06007** [JincorTech/backend-ico-dashboard#183]
> docker-compose up -d
backend-ico-dashboard-develop_mongo_1 is up-to-date
backend-ico-dashboard-develop_redis_1 is up-to-date
backend-ico-dashboard-develop_rpc_1 is up-to-date
backend-ico-dashboard-develop_auth_1 is up-to-date
backend-ico-dashboard-develop_verify_1 is up-to-date
Starting backend-ico-dashboard-develop_ico_1 ... done

then...

> docker-compose exec ico npm i && docker-compose exec ico npm run build
ERROR: No container found for ico_1

?? why getting this error?

**Comment by hlogeon** [comment]
I hope you closed this issue because you figure out the way to avoid this error. In case someone else will look for the solution I'd like to add that you have to run `docker-compose build` in order to build required containers.
