### ISSUE TITLE
add btc to the payment console

### ISSUE THREAD

**Issue by mor888** [JincorTech/backend-ico-dashboard#82]
would be great if can utilize btc relay which can use btc as a payment option

https://github.com/ethereum/btcrelay

**Comment by hlogeon** [comment]
Hello, @mor888 
We are currently implementing integration with coinpayements.net so it will support BTC and 100+ cryptos

**Comment by mor888** [comment]
Is ready? Also can we disable the kyc portion. Easily?

On Feb 23, 2018, at 2:38 PM, Andrey Degtyaruk <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello, @mor888<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmor888&data=02%7C01%7C%7C527b0736eac74787019808d57b0e2449%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636550223018044848&sdata=sHdYai9oLI%2BRnFx36d5U8IJhQQX2rHE46TZGitxbj%2Fo%3D&reserved=0>
We are currently implementing integration with coinpayements.net<http://coinpayements.net> so it will support BTC and 100+ cryptos

**Comment by hlogeon** [comment]
@mor888 
It will be ready approx at 28.02.2018
As for disabling KYC - we will start working on ability to easily disable KYC and partner program right after coinpayments integration. It will take 1-2 business days more.

**Comment by mor888** [comment]
Yikes we were thinking of using it but we are launching on 28

On Feb 23, 2018, at 2:45 PM, Andrey Degtyaruk <notifications@github.com<mailto:notifications@github.com>> wrote:


It will be ready approx at 28.02.2018
As for disabling KYC - we will start working on ability to easily disable KYC and partner program right after coinpayments integration. It will take 1-2 business days more.

**Comment by hlogeon** [comment]
@mor888 
I'm afraid there is no chance to use our dashboard in this case because even our team would not adopt and setup this dashboard in such a short time even if you don't need that changes. It usually takes us 1-4 weeks to customize dashboard for the new ICO.

**Comment by mor888** [comment]
Got it thanks

On Feb 23, 2018, at 3:32 PM, Andrey Degtyaruk <notifications@github.com<mailto:notifications@github.com>> wrote:


@mor888<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmor888&data=02%7C01%7C%7C9756a55801e948d5ea3b08d57b15c122%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636550255721725594&sdata=mb%2BdrHyonPcyqdJiQcv8zxkgLFlm8BlP8N828oujM0s%3D&reserved=0>
I'm afraid there is no chance to use our dashboard in this case because even our team would not adopt and setup this dashboard in such a short time even if you don't need that changes. It usually takes us 1-4 weeks to customize dashboard for the new ICO.

**Comment by CryptoApex** [comment]
@hlogeon Hi, thanks! Looking forward for coinpayment features & KYC disable option.
Keep us update! Thanks for your hard work!

**Comment by hlogeon** [comment]
@xicop9 
Thanks! We really appreciate the interest to our solutions from the community. Stay tunned, big updates are on the way.

**Comment by CryptoApex** [comment]
@hlogeon Awesome! Glad to hear that! Can't wait for the updates ;) Thank you

**Comment by CryptoApex** [comment]
@hlogeon Still no update for disable KYC & coinpayment features?

**Comment by hlogeon** [comment]
@xicop9 This Pull-Request will add this feature #103
It needs some final touches. I hope this nice UI animation will help you to understand implementation :)

![image](https://user-images.githubusercontent.com/3944669/37298275-65a6c242-2652-11e8-9d1a-73b547efef14.png)
