### ISSUE TITLE
Integration with coinpayments.

### ISSUE THREAD

**Issue by Aleserche** [JincorTech/backend-ico-dashboard#86]

**Comment by equitybase** [comment]
possible of integrate with shapeshift? we can provide api info on it

**Comment by hlogeon** [comment]
@equitybase 
Please, create new issue regarding this. We are always open for new integrations if the services are reliable and it can help future ICOs.
Please, provide as much details as you can in new issue. Reason, use-cases, API and any other information which you think can help us in development.

**Comment by mor888** [comment]
As of this integration when do you think it will be ready?

On Feb 20, 2018, at 3:09 PM, Andrey Degtyaruk <notifications@github.com<mailto:notifications@github.com>> wrote:


@equitybase<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fequitybase&data=02%7C01%7C%7Cea4dcfef3e3145553a9508d578b70602%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636547649820093912&sdata=D9qwWiLL7N9I9z87Maf4V5hPdA5CboGGGhrACDSjAzA%3D&reserved=0>
Please, create new issue regarding this. We are always open for new integrations if the services are reliable and it can help future ICOs.
Please, provide as much details as you can in new issue. Reason, use-cases, API and any other information which you think can help us in development.

**Comment by hlogeon** [comment]
@equitybase @mor888 
It depends on complexity, demand, free time of developers and many other factors so it's a bit hard to predict. I think we can do it by the end of March but I cannot give you any guarantee. 
It would be much faster if one of our customers(current or future) will ask for this implementation so we get financial sources and will be able to do it not just like hobby in spare time but spend some business hours on this issue.
Currently you are the first person asking for this and it doesn't seems to be enough for rapid implementation. On the other hand as I said above your request looks reasonable and I think it will make this dashboard more attractive.

**Comment by mor888** [comment]
As of financial incentives what your guys looking for?

On Feb 20, 2018, at 3:32 PM, Andrey Degtyaruk <notifications@github.com<mailto:notifications@github.com>> wrote:


It depends on complexity, demand, free time of developers and many other factors so it's a bit hard to predict. I think we can do it by the end of March but I cannot give you any guarantee.
It would be much faster if one of our customers(current or future) will ask for this implementation so we get financial sources and will be able to do it not just like hobby in spare time but spend some business hours on this issue.
Currently you are the first person asking for this and it doesn't seems to be enough for rapid implementation. On the other hand as I said above your request looks reasonable and I think it will make this dashboard more attractive.

**Comment by hlogeon** [comment]
@equitybase @mor888 
We need some time for evaluation of the feature. You can email me to tech@jincor.com and we will discuss and find the best option.

**Comment by hlogeon** [comment]
https://github.com/JincorTech/backend-ico-dashboard/pull/103
